<?php
return array(
    '2015' => [
        'January 1'   => ['name' => 'New Year\'s Day'],
        'January 19'  => ['name' => 'Martin Luther King Day'],
        'February 16' => ['name' => 'Presidents\' Day'],
        'May 25'      => ['name' => 'Memorial Day'],
        'July 3'      => ['name' => 'Independence Day (observed)'],
        'July 4'      => ['name' => 'Independence Day'],
        'September 7' => ['name' => 'Labor Day'],
        'October 12'  => ['name' => 'Columbus Day'],
        'November 11' => ['name' => 'Veterans Day'],
        'November 26' => ['name' => 'Thanksgiving Day'],
        'December 25' => ['name' => 'Christmas Day'],
    ],
    '2016' => [
        'January 1'   => ['name' => 'New Year\'s Day'],
        'January 18'  => ['name' => 'Martin Luther King Day'],
        'February 15' => ['name' => 'Presidents\' Day'],
        'May 30'      => ['name' => 'Memorial Day'],
        'July 4'      => ['name' => 'Independence Day'],
        'September 5' => ['name' => 'Labor Day'],
        'October 10'  => ['name' => 'Columbus Day'],
        'November 11' => ['name' => 'Veterans Day'],
        'November 24' => ['name' => 'Thanksgiving Day'],
        'December 25' => ['name' => 'Christmas Day'],
        'December 26' => ['name' => 'Christmas Day (observed)'],
    ],
    '2017' => [
        'January 1'   => ['name' => 'New Year\'s Day'],
        'January 2'   => ['name' => 'New Year\'s Day (observed)'],
        'January 16'  => ['name' => 'Martin Luther King Day'],
        'February 20' => ['name' => 'Presidents\' Day'],
        'May 29'      => ['name' => 'Memorial Day'],
        'July 4'      => ['name' => 'Independence Day'],
        'September 4' => ['name' => 'Labor Day'],
        'October 9'   => ['name' => 'Columbus Day'],
        'November 10' => ['name' => 'Veterans Day (observed)'],
        'November 11' => ['name' => 'Veterans Day'],
        'November 23' => ['name' => 'Thanksgiving Day'],
        'December 25' => ['name' => 'Christmas Day'],
    ],
    '2018' => [
        'January 1'   => ['name' => 'New Year\'s Day'],
        'January 15'  => ['name' => 'Martin Luther King Day'],
        'February 19' => ['name' => 'Presidents\' Day'],
        'May 28'      => ['name' => 'Memorial Day'],
        'July 4'      => ['name' => 'Independence Day'],
        'September 3' => ['name' => 'Labor Day'],
        'October 8'   => ['name' => 'Columbus Day'],
        'November 11' => ['name' => 'Veterans Day'],
        'November 12' => ['name' => 'Veterans Day (observed)'],
        'November 22' => ['name' => 'Thanksgiving Day'],
        'December 25' => ['name' => 'Christmas Day'],
    ],
    '2019' => [
        'January 1'   => ['name' => 'New Year\'s Day'],
        'January 21'  => ['name' => 'Martin Luther King Day'],
        'February 18' => ['name' => 'Presidents\' Day'],
        'May 27'      => ['name' => 'Memorial Day'],
        'July 4'      => ['name' => 'Independence Day'],
        'September 2' => ['name' => 'Labor Day'],
        'October 14'  => ['name' => 'Columbus Day'],
        'November 11' => ['name' => 'Veterans Day'],
        'November 28' => ['name' => 'Thanksgiving Day'],
        'December 25' => ['name' => 'Christmas Day'],
    ],
    '2020' => [
        'January 1'   => ['name' => 'New Year\'s Day'],
        'January 20'  => ['name' => 'Martin Luther King Day'],
        'February 17' => ['name' => 'Presidents\' Day'],
        'May 25'      => ['name' => 'Memorial Day'],
        'July 3'      => ['name' => 'Independence Day (observed)'],
        'July 4'      => ['name' => 'Independence Day'],
        'September 7' => ['name' => 'Labor Day'],
        'October 12'  => ['name' => 'Columbus Day'],
        'November 11' => ['name' => 'Veterans Day'],
        'November 26' => ['name' => 'Thanksgiving Day'],
        'December 25' => ['name' => 'Christmas Day'],
    ],
);
